name: Trigger auto deployment for juniorj-ca

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/juniorj-ca-AutoDeployTrigger-8333b427-b5fd-480e-8fa9-d8405b5d8c1c.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: juniorj.azurecr.io
          username: ${{ secrets.JUNIORJCA_REGISTRY_USERNAME }}
          password: ${{ secrets.JUNIORJCA_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: juniorj.azurecr.io/samples/node:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.JUNIORJCA_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n juniorj-ca -g juniorjRG --server juniorj.azurecr.io --username  ${{ secrets.JUNIORJCA_REGISTRY_USERNAME }} --password ${{ secrets.JUNIORJCA_REGISTRY_PASSWORD }}
            az containerapp update -n juniorj-ca -g juniorjRG --image juniorj.azurecr.io/samples/node:${{ github.sha }}
